dnd:
  api:
    key: JNG7yMG1pkxS5OjVYoj73FwfYXTqqAAi
server:
  address: 172.30.1.26
  port: 18080
spring:
  datasource2:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1q2w3e4r!
    url: jdbc:mysql://localhost:3306/dnd_mb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
  profiles:
    active: ch
