dnd:
  api:
    key: JNG7yMG1pkxS5OjVYoj73FwfYXTqqAAi
  secret:
    key: ZG5kcHJvamVjdGtleV9pbl9maXJzdA==
    names: dndprojectkey_in_first
server:
  port: 18080
  ssl:
    enabled: true
    key-store: src/main/resources/keys/dndproject.keystore # 1번에서 생성한 Key store 경로와 파일명을 적어줍니다. 
    key-store-password: chpark  # 1번에서 생성한 Key store의 비밀번호를 적어줍니다.
    key-password: chpark # 1번에서 생성한 키스토어의 마지막의 키 비밀번호
    key-alias: tomcat # 키 스토어 별칭
    trust-store: src/main/resources/keys/dndproject.ts # 2번에서 생성한 Trust-Store 경로
    trust-store-password: chpark # Trust-Store 비밀번호
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1q2w3e4r!
    url: jdbc:mysql://35.188.117.31:3306/dnd_mb?serverTimezone=UTC&characterEncoding=UTF-8
    username: dndadmin
  profiles:
    active: local
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false