spring:
  rabbitmq:
      host: 192.168.99.100
      username: guest   
      password: guest
  datasource:
      url : jdbc:mariadb://192.168.99.100:33301/data_main      
      username : root
      password : g@KgUnHhcYUYu7.
  